#!/bin/sh

echo "setting xrandr dpi" | systemd-cat -t xprofile -p info
xrandr --dpi 168

echo "configuring dpi for gui toolkits" | systemd-cat -t xprofile -p info
# export GDM_SCALE=2
# export ELM_SCALE=2
# export QT_AUTO_SCREEN_SCALE_FACTOR=1

# don't need to do this because I am currently using xfce4-power-manager in i3
echo "configuring monitor to turn off after idle threshold" | systemd-cat -t xprofile -p info
# xset dpms 0 0 600

echo "configuring natural scrolling" | systemd-cat -t xprofile -p info
# builtin touchpad on x1 carbon (possibly other linux machines)
xinput --set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
# my external mouse at the office
xinput --set-prop "pointer:HID 0c45:7403" "libinput Natural Scrolling Enabled" 1
