#!/bin/sh

dpi=168
echo "setting dpi to $dpi with xrandr" | systemd-cat -t xprofile -p info
xrandr --dpi $dpi

echo "configuring natural scrolling" | systemd-cat -t xprofile -p info
# builtin touchpad on x1 carbon (possibly other linux machines)
xinput --set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
# my external mouse at the office
xinput --set-prop "pointer:HID 0c45:7403" "libinput Natural Scrolling Enabled" 1
